urls.py
from django.conf.urls.defaults import *
from culinary.models import *
from culinary.views import PostView, Main, ArchiveMonth

urlpatterns = patterns("dbe.culinary.views",
   (r"^post/(?P<dpk>\d+)/$", PostView.as_view(), {}, "post"),
   (r"^archive_month/(\d+)/(\d+)/$", ArchiveMonth.as_view(), {},
    "archive_month"),
   (r"^$", Main.as_view(), {}, "main"),
)

models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from django.core.mail import send_mail
from culinary.utils import *
from culinary.countries import CountryField

notify = False


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __unicode__(self):
        return self.name


class IngredientAmount(models.Model):
    def __str__(self):
        return ('%s: %s' % (self.ingredient.name, self.amount))
    ingredient = models.ForeignKey(Ingredient)
    amount = models.CharField(max_length=100)  # e.g, `250 ml.` or `1 kg`'


class Post(BaseModel):
    title = models.CharField(max_length=60)
    preview_picture = models.CharField(max_length=100)  # Link for preview
    cuisine = CountryField()  # e.g. `Russian` or `Japan`
    yields = models.PositiveSmallIntegerField()  # e.g `Two big burgers`
    cooktime = models.PositiveSmallIntegerField()  # e.g `About 30 minutes`
    description = models.TextField()  # e.g `My favorite breakfast`
    ingredients = models.ForeignKey(IngredientAmount)  # e.g `Fish`
    body = models.TextField()  # Content in the form of list of steps
    serving_suggestions = models.TextField()  # e.g `Serve immediately`
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self):
        return self.title


class Comment(BaseModel):
    author = models.CharField(max_length=60, blank=True)
    body = models.TextField()
    post = models.ForeignKey(Post, related_name="comments",
                            blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return "%s: %s" % (self.post, self.body[:60])

    def save(self, *args, **kwargs):
        """Email when a comment is added."""
        if notify:
            tpl = "Comment was was added to '%s' by '%s': \n\n%s"
            message = tpl % (self.post, self.author, self.body)
            from_addr = "no-reply@mydomain.com"
            recipient_list = ["myemail@mydomain.com"]
            send_mail("New comment added", message, from_addr, recipient_list)
        super(Comment, self).save(*args, **kwargs)

forms.py
from django.forms import *
from culinary.models import *


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        exclude = ["post"]

    def clean_author(self):
        return self.cleaned_data.get("author") or "Anonymous"

views.py
import time
from calendar import month_name
from culinary.models import *
from culinary.forms import *
from culinary.utils import *
from culinary.mcbv.list import ListView
from culinary.mcbv.list_custom import DetailListCreateView


class PostView(DetailListCreateView):
    """Show post, associated comments and an 'add comment' form."""
    detail_model = Post
    list_model = Comment
    modelform_class = CommentForm
    related_name = "comments"
    fk_attr = "post"
    template_name = "post.html"


class Main(ListView):
    list_model = Post
    paginate_by = 10
    template_name = "list.html"

    def months(self):
        """Make a list of months to show archive links."""
        if not Post.obj.count():
            return list()
        current_year, current_month = time.localtime()[:2]
        first = Post.obj.order_by("created")[0]
        first_year = first.created.year
        first_month = first.created.month
        months = list()
        for year in range(current_year, first_year - 1, -1):
            start, end = 12, 0
            if year == current_year:
                start = current_month
            if year == first_year:
                end = first_month - 1
            for month in range(start, end, -1):
                if Post.obj.filter(created__year=year, created__month=month):
                    months.append((year, month, month_name[month]))
        return months


class ArchiveMonth(Main):
    paginate_by = None

    def get_list_queryset(self):
        year, month = self.args
        return Post.obj.filter(created__year=year,
                                created__month=month).order_by("created")

templates/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    {% block extrahead %}{% endblock %}
    <link rel="stylesheet" href="{{ STATIC_URL }}blog.css" type="text/css" media="screen" charset="utf-8" />

</head>

<body>

    <!-- SIDEBAR -->
    <div id="sidebar"> {% block sidebar %}{% endblock %} </div>

    <div id="container">

        <!-- MENU -->

        <div id="menu">
            {% block nav-global %}

                <h3><a href="/">Culinary blog</a></h3>
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}">Admin</a>
                    <a href="#">Add recipe</a>
                    <a href="#">Add gallery</a>

                {% endif %}

            {% endblock %}
        </div>

        <!-- CONTENT -->

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

templates/culinary/bbase.html
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <title>{% block title %}Blog{% endblock %}</title>
    {% block extrahead %}{% endblock %}
    <link rel="stylesheet" href="/media/css/blog.css" type="text/css" media="screen" charset="utf-8" />

</head>

<body>

    <!-- SIDEBAR -->
    <div id="sidebar"> {% block sidebar %}{% endblock %} </div>

    <div id="container">

        <!-- MENU -->

        <div id="menu">
            {% block nav-global %}

                <h3>MyBlog</h3>
                {% if user.is_staff %}
                    <a href="{% url 'admin:index' %}">Admin</a>
                    <a href="{% url 'admin:blog_post_add' %}">Add post</a>
                {% endif %}

            {% endblock %}
        </div>

        <!-- CONTENT -->

        <div id="content">
            {% block content %}{% endblock %}
        </div>
    </div>

</body>
</html>

templates/list.html
{% extends "bbase.html" %}

{% block extrahead %}
    <link rel="stylesheet" href="{{ STATIC_URL }}blog.css" type="text/css" media="screen" charset="utf-8" />
{% endblock %}

<!-- SIDEBAR -->

{% block sidebar %}
    <div id="sidebar">
        Monthly Archive
        <p>
        {% for ym in view.months %}
            {% ifchanged ym.0 %} {{ ym.0 }} <br /> {% endifchanged %}
            <a href="{% url 'archive_month' ym.0 ym.1 %}">{{ ym.2 }}</a> <br />
        {% endfor %}
        </p>
    </div>
{% endblock %}

<!-- LIST OF POSTS -->

{% block content %}
    <div class="main">
            {% for post in post_list %}
                <div class="title"><a href="{% url 'post' post.pk %}">{{ post.title }}</a></div>
                <ul>
                    <div class="time">{{ post.created }}</div>
                    <div class="picture"><img src="{{ post.preview_picture }}" height="300px" /></div>
                    <div class="body">{{ post.body|linebreaks }}</div>
                    <div class="commentlink">
                        <a href="{% url 'post' post.pk %}">Comments ({{ post.comments.count }})</a>
                    </div>
                </ul>
            {% endfor %}

        {% include "paginator.html" %}
    </div>
{% endblock %}

templates/paginator.html
        {% if object_list and paginator.num_pages > 1 %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}{{ extra_vars }}">prev &lt;&lt; </a>
                {% endif %}

                <span class="current">
                    &nbsp;Page {{ page_obj.number }} of {{ paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}{{ extra_vars }}"> &gt;&gt; next</a>
                {% endif %}
            </span>
        </div>
        {% endif %}

templates/post.html
{% extends "bbase.html" %}
{% block content %}
    <div class="main">

        <div class="title">Recipe Of {{ post.title }}</div>
        <ul>
            <div class="cuisine">Cuisine: {{ post.cuisine }}</div>
            <div class="yields">Yields: {{ post.yields }} person(-s)</div>
            <div class="cooktime">Cooktime: {{ post.cooktime }}</div>
        <hr />
            <div class="body">Recipe:<br />{{ post.body|linebreaks }}</div>
        <hr />
            <div class="serving_suggestions">Serving suggestions:<br />{{ post.serving_suggestions }}</div>
            <!--div class="time">{{ post.created }}</div-->
        </ul>

        <hr />

        {% for comment in comment_list %}
            <ul>
                <div class="time">{{ comment.author }}</div>
                <div class="body">{{ comment.body|linebreaks }}</div>
            </ul>
        {% endfor %}


        <div id="reply">
        <form action="" method="POST"> {% csrf_token %}
            <table>
                {{ modelform.as_table }}
            </table>
            <input type="submit" value="Submit" />
        </form>
        </div>
    </div>
{% endblock %}